git_protocol: https
editor: vim
prompt: enabled
pager:
http_unix_socket:
browser:
aliases:
    # pull requests
    vp: pr view
    wp: pr view --web
    ep: pr edit
    cp: pr create
    cdp: pr create --draft
    op: pr checkout
    # issues
    si: issue status
    vi: issue view
    wi: issue view --web
    ci: issue create
    ei: issue edit
    # repos
    wr: repo view --web 

